//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S7Tools.Resources.Strings
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S7Tools.Resources.Strings.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly-typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Action_Clear
        {
            get
            {
                return ResourceManager.GetString("Action_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close
        {
            get
            {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Action_Connect
        {
            get
            {
                return ResourceManager.GetString("Action_Connect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Action_Disconnect
        {
            get
            {
                return ResourceManager.GetString("Action_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Action_Exit
        {
            get
            {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export
        {
            get
            {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Action_Open
        {
            get
            {
                return ResourceManager.GetString("Action_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save
        {
            get
            {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ActivityBar_Connections
        {
            get
            {
                return ResourceManager.GetString("ActivityBar_Connections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ActivityBar_Explorer
        {
            get
            {
                return ResourceManager.GetString("ActivityBar_Explorer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string ActivityBar_LogViewer
        {
            get
            {
                return ResourceManager.GetString("ActivityBar_LogViewer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ActivityBar_Settings
        {
            get
            {
                return ResourceManager.GetString("ActivityBar_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Siemens S7 PLC Tools with Integrated LogViewer.
        /// </summary>
        public static string ApplicationDescription
        {
            get
            {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to S7Tools.
        /// </summary>
        public static string ApplicationTitle
        {
            get
            {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all logs?.
        /// </summary>
        public static string Confirm_ClearLogs
        {
            get
            {
                return ResourceManager.GetString("Confirm_ClearLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string Confirm_Exit
        {
            get
            {
                return ResourceManager.GetString("Confirm_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Please check your settings and try again..
        /// </summary>
        public static string Error_ConnectionFailed
        {
            get
            {
                return ResourceManager.GetString("Error_ConnectionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File not found. Please check the file path and try again..
        /// </summary>
        public static string Error_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration. Please check your settings..
        /// </summary>
        public static string Error_InvalidConfiguration
        {
            get
            {
                return ResourceManager.GetString("Error_InvalidConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LogViewer_Category
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string LogViewer_Filter
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LogViewer_Level
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string LogViewer_Message
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search logs....
        /// </summary>
        public static string LogViewer_Search
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string LogViewer_Timestamp
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Timestamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        public static string LogViewer_Title
        {
            get
            {
                return ResourceManager.GetString("LogViewer_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit
        {
            get
            {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File
        {
            get
            {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help
        {
            get
            {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Menu_Tools
        {
            get
            {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Menu_View
        {
            get
            {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Status_Connected
        {
            get
            {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Status_Disconnected
        {
            get
            {
                return ResourceManager.GetString("Status_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading
        {
            get
            {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select all required profiles.
        /// </summary>
        public static string Status_AllRequiredProfilesNeeded
        {
            get
            {
                return ResourceManager.GetString("Status_AllRequiredProfilesNeeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a serial device.
        /// </summary>
        public static string Status_SerialDeviceRequired
        {
            get
            {
                return ResourceManager.GetString("Status_SerialDeviceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready
        {
            get
            {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading memory region profiles....
        /// </summary>
        public static string Status_LoadingMemoryRegionProfiles
        {
            get
            {
                return ResourceManager.GetString("Status_LoadingMemoryRegionProfiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No profiles available.
        /// </summary>
        public static string Status_NoProfilesAvailable
        {
            get
            {
                return ResourceManager.GetString("Status_NoProfilesAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating job....
        /// </summary>
        public static string Status_CreatingJob
        {
            get
            {
                return ResourceManager.GetString("Status_CreatingJob", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job created.
        /// </summary>
        public static string Status_JobCreated
        {
            get
            {
                return ResourceManager.GetString("Status_JobCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Status_PowerUnknown
        {
            get
            {
                return ResourceManager.GetString("Status_PowerUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error loading profiles: {0}.
        /// </summary>
        public static string Status_ErrorLoadingProfiles
        {
            get
            {
                return ResourceManager.GetString("Status_ErrorLoadingProfiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Status_ErrorCreatingJob
        {
            get
            {
                return ResourceManager.GetString("Status_ErrorCreatingJob", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error scanning ports: {0}.
        /// </summary>
        public static string Status_ErrorScanningPorts
        {
            get
            {
                return ResourceManager.GetString("Status_ErrorScanningPorts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs exported to clipboard.
        /// </summary>
        public static string Status_LogsExportedToClipboard
        {
            get
            {
                return ResourceManager.GetString("Status_LogsExportedToClipboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading profiles....
        /// </summary>
        public static string Status_LoadingProfiles
        {
            get
            {
                return ResourceManager.GetString("Status_LoadingProfiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scanning for ports....
        /// </summary>
        public static string Status_ScanningForPorts
        {
            get
            {
                return ResourceManager.GetString("Status_ScanningForPorts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name is required.
        /// </summary>
        public static string Validation_ProfileNameRequired
        {
            get
            {
                return ResourceManager.GetString("Validation_ProfileNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name already exists.
        /// </summary>
        public static string Validation_ProfileNameExists
        {
            get
            {
                return ResourceManager.GetString("Validation_ProfileNameExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a memory region profile.
        /// </summary>
        public static string Validation_SelectMemoryRegionProfile
        {
            get
            {
                return ResourceManager.GetString("Validation_SelectMemoryRegionProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Job name is required.
        /// </summary>
        public static string Validation_JobNameRequired
        {
            get
            {
                return ResourceManager.GetString("Validation_JobNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Base address must be a valid hexadecimal value.
        /// </summary>
        public static string Validation_BaseAddressHex
        {
            get
            {
                return ResourceManager.GetString("Validation_BaseAddressHex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size must be greater than zero.
        /// </summary>
        public static string Validation_SizeGreaterThanZero
        {
            get
            {
                return ResourceManager.GetString("Validation_SizeGreaterThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Theme_Auto
        {
            get
            {
                return ResourceManager.GetString("Theme_Auto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark
        {
            get
            {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light
        {
            get
            {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch Theme.
        /// </summary>
        public static string Tooltip_SwitchTheme
        {
            get
            {
                return ResourceManager.GetString("Tooltip_SwitchTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Bottom Panel.
        /// </summary>
        public static string Tooltip_ToggleBottomPanel
        {
            get
            {
                return ResourceManager.GetString("Tooltip_ToggleBottomPanel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle Sidebar.
        /// </summary>
        public static string Tooltip_ToggleSidebar
        {
            get
            {
                return ResourceManager.GetString("Tooltip_ToggleSidebar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory region profile must be selected.
        /// </summary>
        public static string Validation_MemoryRegionProfileRequired
        {
            get
            {
                return ResourceManager.GetString("Validation_MemoryRegionProfileRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exactly one segment must be selected for dumping.
        /// </summary>
        public static string Validation_ExactlyOneSegmentRequired
        {
            get
            {
                return ResourceManager.GetString("Validation_ExactlyOneSegmentRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only one segment can be selected per job.
        /// </summary>
        public static string Validation_OnlyOneSegmentAllowed
        {
            get
            {
                return ResourceManager.GetString("Validation_OnlyOneSegmentAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A profile with this name already exists.
        /// </summary>
        public static string Validation_ProfileNameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("Validation_ProfileNameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error validating profile name.
        /// </summary>
        public static string Validation_ErrorValidatingProfileName
        {
            get
            {
                return ResourceManager.GetString("Validation_ErrorValidatingProfileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Test clipboard text.
        /// </summary>
        public static string TestClipboardText
        {
            get
            {
                return ResourceManager.GetString("TestClipboardText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text cut to clipboard.
        /// </summary>
        public static string ClipboardTextCut
        {
            get
            {
                return ResourceManager.GetString("ClipboardTextCut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text copied to clipboard.
        /// </summary>
        public static string ClipboardTextCopied
        {
            get
            {
                return ResourceManager.GetString("ClipboardTextCopied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text pasted from clipboard.
        /// </summary>
        public static string ClipboardTextPasted
        {
            get
            {
                return ResourceManager.GetString("ClipboardTextPasted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady
        {
            get
            {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile selected: {0}.
        /// </summary>
        public static string Status_ProfileSelected
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile '{0}' deleted successfully.
        /// </summary>
        public static string Status_ProfileDeletedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileDeletedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile duplicated: {0}.
        /// </summary>
        public static string Status_ProfileDuplicated
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileDuplicated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile '{0}' set as default.
        /// </summary>
        public static string Status_ProfileSetAsDefault
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileSetAsDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error refreshing profiles.
        /// </summary>
        public static string Status_ErrorRefreshingProfiles
        {
            get
            {
                return ResourceManager.GetString("Status_ErrorRefreshingProfiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles refreshed.
        /// </summary>
        public static string Status_ProfilesRefreshed
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesRefreshed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No profile selected.
        /// </summary>
        public static string Status_NoProfileSelected
        {
            get
            {
                return ResourceManager.GetString("Status_NoProfileSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected profile has no configuration.
        /// </summary>
        public static string Status_SelectedProfileHasNoConfiguration
        {
            get
            {
                return ResourceManager.GetString("Status_SelectedProfileHasNoConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile validation failed: {0}.
        /// </summary>
        public static string Status_ProfileValidationFailed
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileValidationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name cannot be empty.
        /// </summary>
        public static string Status_ProfileNameCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileNameCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name is too long.
        /// </summary>
        public static string Status_ProfileNameTooLong
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileNameTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile name '{0}' is already in use.
        /// </summary>
        public static string Status_ProfileNameAlreadyInUse
        {
            get
            {
                return ResourceManager.GetString("Status_ProfileNameAlreadyInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File dialog service not available.
        /// </summary>
        public static string Status_FileDialogServiceNotAvailable
        {
            get
            {
                return ResourceManager.GetString("Status_FileDialogServiceNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} profile(s) exported to {1}.
        /// </summary>
        public static string Status_ProfilesExportedToFile
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesExportedToFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export failed: Access denied.
        /// </summary>
        public static string Status_ExportFailedAccessDenied
        {
            get
            {
                return ResourceManager.GetString("Status_ExportFailedAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export failed: {0}.
        /// </summary>
        public static string Status_ExportFailed
        {
            get
            {
                return ResourceManager.GetString("Status_ExportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: No valid profiles found in file.
        /// </summary>
        public static string Status_ImportFailedNoValidProfiles
        {
            get
            {
                return ResourceManager.GetString("Status_ImportFailedNoValidProfiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} profile(s) imported from {1}.
        /// </summary>
        public static string Status_ProfilesImportedFromFile
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesImportedFromFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: File not found.
        /// </summary>
        public static string Status_ImportFailedFileNotFound
        {
            get
            {
                return ResourceManager.GetString("Status_ImportFailedFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: Invalid file format.
        /// </summary>
        public static string Status_ImportFailedInvalidFormat
        {
            get
            {
                return ResourceManager.GetString("Status_ImportFailedInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: Access denied.
        /// </summary>
        public static string Status_ImportFailedAccessDenied
        {
            get
            {
                return ResourceManager.GetString("Status_ImportFailedAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import failed: {0}.
        /// </summary>
        public static string Status_ImportFailed
        {
            get
            {
                return ResourceManager.GetString("Status_ImportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string Status_ConnectedToProfile
        {
            get
            {
                return ResourceManager.GetString("Status_ConnectedToProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turning power ON....
        /// </summary>
        public static string Status_TurningPowerOn
        {
            get
            {
                return ResourceManager.GetString("Status_TurningPowerOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power turned ON.
        /// </summary>
        public static string Status_PowerTurnedOn
        {
            get
            {
                return ResourceManager.GetString("Status_PowerTurnedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to turn power ON.
        /// </summary>
        public static string Status_FailedToTurnPowerOn
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToTurnPowerOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Turning power OFF....
        /// </summary>
        public static string Status_TurningPowerOff
        {
            get
            {
                return ResourceManager.GetString("Status_TurningPowerOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power turned OFF.
        /// </summary>
        public static string Status_PowerTurnedOff
        {
            get
            {
                return ResourceManager.GetString("Status_PowerTurnedOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to turn power OFF.
        /// </summary>
        public static string Status_FailedToTurnPowerOff
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToTurnPowerOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reading power state....
        /// </summary>
        public static string Status_ReadingPowerState
        {
            get
            {
                return ResourceManager.GetString("Status_ReadingPowerState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power state: {0}.
        /// </summary>
        public static string Status_PowerStateOnOff
        {
            get
            {
                return ResourceManager.GetString("Status_PowerStateOnOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading state: {0}.
        /// </summary>
        public static string Status_ReadStateError
        {
            get
            {
                return ResourceManager.GetString("Status_ReadStateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not connected to power supply.
        /// </summary>
        public static string Status_NotConnectedToPowerSupply
        {
            get
            {
                return ResourceManager.GetString("Status_NotConnectedToPowerSupply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle: Turning OFF....
        /// </summary>
        public static string Status_PowerCycleTurningOff
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleTurningOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle failed: Could not turn OFF.
        /// </summary>
        public static string Status_PowerCycleFailedCouldNotTurnOff
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleFailedCouldNotTurnOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle: Waiting {0}ms before turning ON....
        /// </summary>
        public static string Status_PowerCycleWaitingBeforeTurningOn
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleWaitingBeforeTurningOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle: Turning ON....
        /// </summary>
        public static string Status_PowerCycleTurningOn
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleTurningOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle failed: Could not turn ON.
        /// </summary>
        public static string Status_PowerCycleFailedCouldNotTurnOn
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleFailedCouldNotTurnOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power cycle: Waiting {0}ms to stabilize....
        /// </summary>
        public static string Status_PowerCycleWaitingToStabilize
        {
            get
            {
                return ResourceManager.GetString("Status_PowerCycleWaitingToStabilize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles path set to: {0}.
        /// </summary>
        public static string Status_ProfilesPathSetTo
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesPathSetTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to set profiles path: Access denied.
        /// </summary>
        public static string Status_FailedToSetProfilesPathAccessDenied
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToSetProfilesPathAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to set profiles path: {0}.
        /// </summary>
        public static string Status_FailedToSetProfilesPath
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToSetProfilesPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opening profiles folder....
        /// </summary>
        public static string Status_OpeningProfilesFolder
        {
            get
            {
                return ResourceManager.GetString("Status_OpeningProfilesFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles path not configured.
        /// </summary>
        public static string Status_ProfilesPathNotConfigured
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesPathNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating profiles folder....
        /// </summary>
        public static string Status_CreatingProfilesFolder
        {
            get
            {
                return ResourceManager.GetString("Status_CreatingProfilesFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles folder opened.
        /// </summary>
        public static string Status_ProfilesFolderOpened
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesFolderOpened", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to open folder: Access denied.
        /// </summary>
        public static string Status_FailedToOpenFolderAccessDenied
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToOpenFolderAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to open folder: {0}.
        /// </summary>
        public static string Status_FailedToOpenFolder
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToOpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles path reset to default.
        /// </summary>
        public static string Status_ProfilesPathReset
        {
            get
            {
                return ResourceManager.GetString("Status_ProfilesPathReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to reset profiles path: {0}.
        /// </summary>
        public static string Status_FailedToResetProfilesPath
        {
            get
            {
                return ResourceManager.GetString("Status_FailedToResetProfilesPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to load settings.
        /// </summary>
        public static string Status_WarningFailedToLoadSettings
        {
            get
            {
                return ResourceManager.GetString("Status_WarningFailedToLoadSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error during {0}: {1}.
        /// </summary>
        public static string Status_ErrorOperation
        {
            get
            {
                return ResourceManager.GetString("Status_ErrorOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string Value_PowerOn
        {
            get
            {
                return ResourceManager.GetString("Value_PowerOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string Value_PowerOff
        {
            get
            {
                return ResourceManager.GetString("Value_PowerOff", resourceCulture);
            }
        }
    }
}
